config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get      'users/terms'          => 'users#terms',         as: 'terms'
  get      '/contents/index_age0' => 'contents#index_age0', as: 'contents_age0'
  get      '/contents/index_age1' => 'contents#index_age1', as: 'contents_age1'
  get      '/contents/index_age2' => 'contents#index_age2', as: 'contents_age2'
  get      '/contents/index_age3' => 'contents#index_age3', as: 'contents_age3'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations:      'users/confirmations'
                                    }
  resources :contents,   only:[:new, :create, :index, :show, :update, :destroy] do
    resource :likes,     only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    resource :comments,  only:[:create]
    delete '/comments/:id' => 'comments#destroy', as: 'destroy_comments'
    collection do
      get 'search'
    end
  end
  resources :users,      only:[:index, :show, :update, :destroy] do
    get 'user_likes'      => 'users#user_likes'
    get 'user_favorites'  => 'users#user_favorites'
    get 'user_followings' => 'users#user_followings'
    get 'user_followers'  => 'users#user_followers'
    collection do
      get 'search'
    end
  end
  resources :relationships, only:[:create, :destroy]
  resources :messages,      only:[:create]
  resources :rooms,         only:[:create,:show]
  resources :notifications, only:[:index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  validates  :user_id,    presence: true
  validates  :body,       presence: true
  validates  :target_age, presence: true

  belongs_to :user
  belongs_to :category
  has_many   :content_images, dependent: :destroy
  accepts_attachments_for :content_images, attachment: :image
  has_many   :comments,       dependent: :destroy
  has_many   :likes,          dependent: :destroy
  has_many   :favorites,      dependent: :destroy
  has_many   :notifications,  dependent: :destroy

  # user_idが存在する確認
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # いいね通知
  def create_notification_like(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and content_id = ? and action = ? ', current_user.id,
                               user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        content_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      # バリデーションが実行された結果、エラーが無い場合trueを返し，エラーが発生した場合falseを返す
      notification.save if notification.valid?
    end
  end

  # お気に入り通知
  def create_notification_favorite(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and content_id = ? and action = ? ', current_user.id,
                               user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        content_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  # コメント通知
  def create_notification_comment(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(content_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      content_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/contents_controller.rb
# frozen_string_literal: true
include ActionView::Helpers::UrlHelper

class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: %i[index search]

  def new
    @content = Content.new
  end

  def index
    if request.query_parameters.any?
      index_age(request.query_parameters[:age])
    else
      contents  = Content.page(params[:page]).per(15)
      @target_age = ['0歳', '1歳', '2歳', '3歳', '4歳以上']
      @contents = contents.all.order(created_at: 'DESC')
      @comment  = Comment.new
    end 
  end 
  
  def create
    @content = Content.new(content_params)
    @content.user_id = current_user.id
    if @content.save
      redirect_to contents_path, notice: '投稿しました'
    else
      render new_content_path
    end
  end

  def show
    @content     = Content.find(params[:id])
    @comment     = Comment.new
    @comment_all = Comment.where(content_id: [@content])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update(content_params)
      redirect_to content_path(@content.id), notice: '変更を保存しました'
    else
      redirect_to content_path(@content.id), alert: '変更に失敗しました'
    end
  end

  def destroy
    user = Content.find(params[:id]).user
    if current_user == user
      Content.find(params[:id]).destroy
      redirect_to contents_path, notice: '投稿を削除しました'
    end
  end

  def search
    results = @q.result.page(params[:page]).per(15)
    @results = results.all.order(created_at: 'DESC')
    @comment = Comment.new
  end

  private

  def set_q
    @q = Content.ransack(params[:q])
  end

  def content_params
    params.require(:content).permit(:body, :target_age, :category_id, content_images_images: [])
  end
  
  def index_age(age)
    contents = Content.where(target_age: "#{age}歳").page(params[:page]).per(15)
    @contents = contents.order(created_at: 'DESC')
    @comment  = Comment.new
  end 
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
end

app/views/contents/index.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <%= render "layouts/nav" %>
  <%= search_form_for @q, url: search_contents_path do |f| %>
    <div class="row mx-auto mt-3 px-0">
      <div class="col-md-4 offset-md-4">
        <div class="mb-2 btn btn-outline-secondary form-control" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">離乳食の投稿を検索する<i class="fas fa-search pl-3"></i></div>
      </div>
      <div class="collapse col-md-6 offset-md-3" id="collapseExample">
        <%= f.search_field :body_cont, :placeholder => "ワード検索", class: "form-control mb-3"  %>
        <%= f.collection_select(:category_id_eq, Category.all, :id, :ingredient, {prompt: "食材カテゴリ"}, {class: "form-control mb-3"}) %>
        <%= f.select :target_age_eq, ['0歳', '1歳', '2歳', '3歳', '4歳以上'], { include_blank: '選択してください'}, {class: "form-control mb-2"} %>
        <%= f.submit '検索', class: "btn btn-info form-control" %>
      </div>
    </div>
  <% end %>
  <%= render "layouts/contents_index", contents: @contents %>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @contents %>
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/contents/new.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <div class="col-lg-6 offset-lg-3 mx-auto mt-3 px-0 text-center content-new-circle">
    <div class="top-heading pt-3">
      <%= image_tag 'new_content.jpeg', size: "250x200", class: 'img-fluid rounded top-image' %>
      <!--<h3 id="arctext" class="arctext mb-3 font-weight-bold" >| Make and enjoy |</h3>-->
      <!--<h1 class="pt-2 pb-2 font-weight-bold">PakuPaku</h1>-->
      <!--<h3 id="arctext-2" class="arctext font-weight-bold mt-3 pb-3">Baby Food</h3>-->
    </div>
  </div>
  <div class="card col-lg-6 offset-lg-3 mx-auto px-0">
    <div class="card-body pt-0">
      <%= form_with model: @content, local:true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="form-group row mt-5">
          <label class="col-lg-3 col-form-label text-md-right"><%= f.label :画像 %></label>
          <div class="col-lg-9">
            <div class="item_image_btn">
              <%= f.attachment_field :content_images_images, multiple: true, id: "file" %>
            </div>
            <div id="img_field" onClick="$('#file').click()" >
              <p>画像選択</p>
            </div>
          </div>
        </div>

        <div class="form-group row pt-3 pb-3">
          <label class="col-lg-3 col-form-label text-md-right"><%= f.label :キャプション %></label>
          <div class="col-lg-9">
            <%= f.text_area :body, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-3 col-form-label text-md-right"><%= f.label :食材カテゴリ %></label>
          <div class="col-lg-9 pt-2">
            <%= f.collection_select(:category_id, Category.all, :id, :ingredient, {prompt: "選択してください"}, {class: "form-control"}) %>
            <small class="form-text">※ 使用されている食材のカテゴリを選択してください</small>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-3 col-form-label text-md-right"><%= f.label :お子様の年齢 %></label>
          <div class="col-lg-9 pt-2">
            <%= f.select :target_age, ['0歳', '1歳', '2歳', '3歳', '4歳以上'], { include_blank: '選択してください'}, {class: 'form-control'} %>
            <small class="form-text">※ 投稿の対象としたいお子様のご年齢を選択してください</small>
          </div>
        </div>

        <div class="actions text-right pr-4">
          <%= f.submit "投稿", class: "btn btn-info mt-4 mb-4" %>
        </div>

      <% end %>
    </div>
  </div>

  <%= render "layouts/footer" %>
</div>

<script type="text/javascript">
   $('#arctext').arctext({radius: 300});
   $('#arctext-2').arctext({radius: 300, dir: -1});
</script>

app/views/contents/search.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <% @results.each do |content| %>
    <div class="card col-lg-6 offset-lg-3 mx-auto mt-3 px-0">
      <div class="card-header">
        <div class="row">
          <div class="col-2">
            <%= link_to user_path(content.user) do %>
              <%= attachment_image_tag content.user, :profile_image, :fill, 40, 40, fallback: "no_image.png", class:"rounded-circle"; %>
            <% end %>
          </div>
          <div class="col-5 text-left font-weight-bold">
            <%= link_to user_path(content.user), class: "deco-none" do %>
              <%= content.user.user_name %>
            <% end %>
          </div>
          <div class="col-5 text-right">
            <div class ="text-black-50"><%= content.target_age %>向けの投稿</div>
          </div>
        </div>
      </div>
        <% if content.content_images.present? %>
        <div class="slider">
          <% content.content_images.each do |image| %>
            <%= link_to content_path(content.id) do %>
              <%= attachment_image_tag image, :image, class:"card-img-top"; %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <div class="card-body pt-0">
        <div class="card-text border-bottom pt-3"><%= raw Rinku.auto_link(simple_format(content.body)) %></div>
        <div class="row pt-4">
        <div class="col-4">
          <div class="text-black-50 small"><%= date_format(content.created_at) %></div>
        </div>
        <div class="col-8">
          <div class="row">
            <div id='like-button_<%= content.id %>' class="col-6 text-right">
            <%= render "layouts/like", content: content %>
            </div>
            <div id='favorite-button_<%= content.id %>' class="col-6">
              <%= render "layouts/favorite", content: content %>
            </div>
          </div>
        </div>
      </div>
      <%= render "layouts/comment", comment: @comment, content: content %>
      </div>
    </div>
  <% end %>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @results %>
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/contents/show.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <div class="card col-lg-6 offset-lg-3 mx-auto mt-4 px-0">
    <div class="card-header">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@content.user), class: "deco-none" do %>
            <%= attachment_image_tag @content.user, :profile_image, :fill, 40, 40, fallback: "no_image.png", class:"rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-5 text-left font-weight-bold">
          <%= @content.user.user_name %>
        </div>
        <div class="col-5 text-right">
          <div class ="text-black-50"><%= @content.target_age %>向けの投稿</div>
          <% if @content.user_id == current_user.id %>
            <div class="dropdown">
              <h5 class="dropdown-toggle" data-toggle="dropdown"></h5>
              <div class="dropdown-menu dropdown-menu-right bg-light">
                <div class="btn btn-outline-info ml-3" data-toggle="modal" data-target="#content-edit-modal">編集</div>
                <%= link_to "削除", content_path(@content), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-outline-danger ml-1" %>
              </div>
            </div>
          <% end %>
        </div>
        <%= render "layouts/content_edit" %>
      </div>
    </div>
      <% if @content.content_images.present? %>
          <div class="slider">
            <% @content.content_images.each do |image| %>
              <%= attachment_image_tag image, :image, class:"card-img-top"; %>
            <% end %>
          </div>
        <% end %>

    <div class="card-body pt-0">
      <div class="card-text border-bottom pt-3"><%= raw Rinku.auto_link(simple_format(@content.body)) %></div>
      <div class="row pt-2">
        <div class="col-6">
          <div class="text-black-50 small"><%= date_format(@content.created_at) %></div>
        </div>
        <div class="col-6">
          <div class="row">
            <div id='like-button_<%= @content.id %>' class="col-6 text-right">
            <%= render "layouts/like", content: @content %>
            </div>
            <div id='favorite-button_<%= @content.id %>' class="col-6">
              <%= render "layouts/favorite", content: @content %>
            </div>
          </div>
        </div>
      </div>
      <%= render "layouts/comment", comment: @comment, content: @content %>
      <div class="row">
        <div class="col-6">
          <div class="pt-3 small text-black-50"><%= @comment_all.count %> 件コメント</div>
        </div>
        <div class="col-6">
          <h6 class="pt-3 m-0 small text-black-50" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
        </div>
      </div>

      <% @comment_all.first(2).each do |comment| %>
        <div class="border-bottom small pt-2 pb-2">
          <% unless comment.id.nil? %>
            <div class="form-inline">
              <div class="col-2">
                <%= link_to user_path(comment.user), class: "deco-none pr-3" do %>
                    <%= attachment_image_tag comment.user, :profile_image, :fill, 32, 32, fallback: "no_image.png", class:"rounded-circle"; %>
                  <% end %>
              </div>
              <div class="col-4 font-weight-bold">
                <%= link_to user_path(comment.user), class: "deco-none pr-3" do %>
                  <%= comment.user.user_name %>
                <% end %>
              </div>
              <div class="col-1 text-right">
                <% if comment.user == current_user %>
                　<!--remote: trueは削除-->
                  <%= link_to content_destroy_comments_path(@content, comment), method: :delete, class: "comment_destroy" do %>
                    <i class="fas fa-trash" style="color: black;"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="col-4 text-black-50">
                <%= date_format(comment.created_at) %>
              </div>
              <div class="col-10 offset-2">
                <%= comment.comment %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="collapse" id="collapseExample">
        <% @comment_all.offset(2).each do |comment| %>
          <div class="border-bottom small pt-2 pb-2">
            <% unless comment.id.nil? %>
              <div class="form-inline">
                <div class="col-2">
                  <%= link_to user_path(comment.user), class: "deco-none pr-3" do %>
                    <%= attachment_image_tag comment.user, :profile_image, :fill, 32, 32, fallback: "no_image.png", class:"rounded-circle"; %>
                  <% end %>
                </div>
                <div class="col-4 font-weight-bold">
                  <%= link_to user_path(comment.user), class: "deco-none pr-3" do %>
                    <%= comment.user.user_name %>
                  <% end %>
                </div>
                <div class="col-1 text-right">
                  <% if comment.user == current_user %>
                    <!--remote: trueは削除-->
                    <%= link_to content_destroy_comments_path(@content, comment), method: :delete, class: "comment_destroy" do %>
                      <i class="fas fa-trash" style="color: black;"></i>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-4 text-black-50">
                  <%= date_format(comment.created_at) %>
                </div>
                <div class="col-10 offset-2">
                  <%= comment.comment %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

    </div>
  </div>
  <%= render "layouts/footer" %>
</div>