config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get      'users/terms'          => 'users#terms',         as: 'terms'
  get      '/contents/index_age0' => 'contents#index_age0', as: 'contents_age0'
  get      '/contents/index_age1' => 'contents#index_age1', as: 'contents_age1'
  get      '/contents/index_age2' => 'contents#index_age2', as: 'contents_age2'
  get      '/contents/index_age3' => 'contents#index_age3', as: 'contents_age3'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations:      'users/confirmations'
                                    }
  resources :contents,   only:[:new, :create, :index, :show, :update, :destroy] do
    resource :likes,     only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    resource :comments,  only:[:create]
    delete '/comments/:id' => 'comments#destroy', as: 'destroy_comments'
    collection do
      get 'search'
    end
  end
  resources :users,      only:[:index, :show, :update, :destroy] do
    get 'user_likes'      => 'users#user_likes'
    get 'user_favorites'  => 'users#user_favorites'
    get 'user_followings' => 'users#user_followings'
    get 'user_followers'  => 'users#user_followers'
    collection do
      get 'search'
    end
  end
  resources :relationships, only:[:create, :destroy]
  resources :messages,      only:[:create]
  resources :rooms,         only:[:create,:show]
  resources :notifications, only:[:index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  attachment :profile_image

  validates :user_name,    presence: true
  validates :email,        presence: true,
                           uniqueness: true,
                           format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  has_many  :contents,     dependent: :destroy
  has_many  :comments,     dependent: :destroy
  has_many  :likes,        dependent: :destroy
  has_many  :favorites,    dependent: :destroy

  has_many :relationships, dependent: :destroy
  has_many :followings,    through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers,     through: :reverse_of_relationships, source: :user, dependent: :destroy

  has_many :messages,      dependent: :destroy
  has_many :entries,       dependent: :destroy

  # 自分からの通知
  has_many :active_notifications,  class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  
  # Likeテーブルにuser_idが存在しているか確認
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
  
  # Favoriteテーブルにuser_idが存在しているか確認
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # もし引数に入ってきたother_userが自分じゃなければ、Relationshipテーブルからfollow_idがother_userのidを取得し、なければ作成する
  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end
  
  # もしRelationshipテーブルからフォローを外したいユーザーidが見つかれば、フォローを解除する
  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # followingsに引数に入ってきたother_userはあるかどうかを返す
  def following?(other_user)
    followings.include?(other_user)
  end
  
  # idだけの部分が何のidを指しているかは、このメソッドを呼び出す部分のuser_id -> @user.create_notification_follow(current_user)　なら@userのid
  # 条件でNotificationテーブルからレコードを探してきて、その条件に合うレコードがなければ、バリデーションチェックして新しく作成
  def create_notification_follow(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  # SNS認証の情報を入れるメソッド
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email     = auth.info.email
      user.user_name = auth.info.name
      user.password  = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end
    
    #メール認証後にそのままログインさせるための記述
    #これはメールアドレスを間違って登録してしまった時のため、セキュリティ上この設定になっている
    # GET /resource/confirmation?confirmation_token=abcdef
    def show
      super do
        sign_in(resource) if resource.errors.empty?
      end
    end
  
    def after_confirmation_path_for(resource_name, resource)
      after_sign_in_path_for(resource)
    end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      callback_for(:google)
    end

    def callback_for(provider)
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q, only: %i[index search]

  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def show
    @user        = User.find(params[:id])
    contents     = Content.where(user_id: [@user]).page(params[:page]).per(15)
    @contents    = contents.order(created_at: 'DESC')
    @comment_all = Comment.where(content_id: [@content])
    @comment     = Comment.new
    # ・DM機能　Entryテーブルからログインしているユーザーとshowページのユーザーを取ってくる
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry        = Entry.where(user_id: @user.id)
    # idが一致しなければroomが作られているか確認し、なければnew、あれば@roomIdにすでに作られているroom_idを入れる
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room  = Room.new
        @entry = Entry.new
      end
    end
  end

  # ユーザーがいいねした投稿を全て表示
  def user_likes
    @user        = User.find(params[:user_id])
    @contents    = @user.likes.order(created_at: 'DESC')
    @comment_all = Comment.where(content_id: [@contents])
    @comment     = Comment.new
  end

  def user_favorites
    @user        = User.find(params[:user_id])
    @contents    = @user.favorites.order(created_at: 'DESC')
    @comment_all = Comment.where(content_id: [@contents])
    @comment     = Comment.new
  end

  def user_followings
    @user        = User.find(params[:user_id])
    @users       = @user.followings.order(created_at: 'DESC')
  end

  def user_followers
    @user        = User.find(params[:user_id])
    @users       = @user.followers.order(created_at: 'DESC')
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '変更を保存しました'
    else
      redirect_to user_path(@user.id), alert: '変更に失敗しました'
    end
  end

  def search
    @results = @q.result.page(params[:page]).per(15)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path, notice: 'ユーザーを削除しました'
  end

  def terms; end

  private

  def set_q
    @q = User.ransack(params[:q])
  end

  def user_params
    params.require(:user).permit(:user_name, :sex, :birthday, :profile_image, :introduction, :child_gender, :child_age)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/index.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <%= search_form_for @q, url: search_users_path do |f| %>
    <div class="row mx-auto mt-3 px-0">
      <div class="col-md-6 offset-md-3">
        <div class="input-group">
          <%= f.search_field :user_name_cont, :placeholder => "ユーザー検索", class: "form-control"  %>
          <span class="input-group-btn">
            <%= f.submit '検索', class: "btn btn-outline-secondary" %>
          </span>
        </div>
      </div>
    </div>
  <% end %>
  <% @users.each do |user| %>
    <div class="card col-lg-6 offset-lg-3 mx-auto mt-4 px-0">
      <div class="card-header bg-white">
        <div class="row">
          <div class="col-5">
            <%= link_to user_path(user), class: "deco-none" do %>
              <h6 class="text-left font-weight-bold"><%= user.user_name %></h6>
            <% end %>
          </div>
          <div class="col-2 p-0 text-center">
            <% if current_user.admin? && current_user != user %>
              <%= link_to "削除", user_path(user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "small" %>
            <% end %>
          </div>
          <div class="col-5" id='follow-button_<%= user.id %>'>
            <%= render "layouts/follow", user: user %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row no-gutters border-bottom">
          <div class="col-3 pb-3">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.png", class:"rounded-circle"; %>
            <% end %>
          </div>
          <div class="col-3 small text-center">投稿数</br><%= user.contents.count %></div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followings_path(user), class: "deco-none" do %>
              フォロー</br><div id="following-count_<%= user.id %>"><%= user.followings.count %></div>
            <% end %>
          </div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followers_path(user), class: "deco-none" do %>
              フォロワー</br><div id="follower-count_<%= user.id %>"><%= user.followers.count %></div>
            <% end %>
          </div>
        </div>
        <div class="row p-2">
          <div class="col-4">
            <%= user.user_name %>
          </div>
          <div class="col-8">
            <p class="text-black-50 small"><%= user.created_at.to_s(:datetime_jp) %>から</br>
            PAKUPAKUを利用しています
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <%= user.introduction %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @users %>
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/users/search.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <% @results.each do |user| %>
    <div class="card col-lg-6 offset-lg-3 mx-auto mt-4 px-0">
      <div class="card-header bg-white">
        <div class="row">
          <div class="col-7">
            <%= link_to user_path(user), class: "deco-none" do %>
              <h6 class="text-left font-weight-bold"><%= user.user_name %></h6>
            <% end %>
          </div>
          <div class="col-5" id='follow-button_<%= user.id %>'>
            <%= render "layouts/follow", user: user %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row no-gutters border-bottom">
          <div class="col-3 pb-3">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.png", class:"rounded-circle"; %>
            <% end %>
          </div>
          <div class="col-3 small text-center">投稿数</br><%= user.contents.count %></div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followings_path(user), class: "deco-none" do %>
              フォロー</br><div id="following-count_<%= user.id %>"><%= user.followings.count %></div>
            <% end %>
          </div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followers_path(user), class: "deco-none" do %>
              フォロワー</br><div id="follower-count_<%= user.id %>"><%= user.followers.count %></div>
            <% end %>
          </div>
        </div>
        <div class="row p-2">
          <div class="col-4">
            <%= link_to user_path(user), class: "deco-none" do %>
              <%= user.user_name %>
            <% end %>
          </div>
          <div class="col-8">
            <p class="text-black-50 small"><%= user.created_at.to_s(:datetime_jp) %>から</br>
            PAKUPAKUを利用しています
            </p>
            
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <%= user.introduction %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @results %>
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/users/show.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <div class="card col-lg-6 offset-lg-3 mx-auto mt-4 px-0">
    <div class="card-header bg-white">
      <div class="row">
        <div class="col-6">
          <h5 class="text-left font-weight-bold"><%= @user.user_name %></h5>
        </div>
        <% if @user == current_user %>
          <div class="col-4 text-center">
            <div class="text-black-50 pt-2" data-toggle="modal" data-target="#profile-edit-modal">
             <h5 class="fas fa-user-edit"></h5>
            </div>
            <%= render "layouts/user_edit" %>
          </div>
          <div class="col-2">
            <%= link_to destroy_user_session_path, method: :delete, class: "deco-none" do %>
              <h5 class="fas fa-sign-out-alt text-black-50 pt-2" data-toggle="tooltip" title="ログアウト"></h5>
            <% end %>
          </div>
        <% end %>
        <div class="col-5">
          <div id='follow-button_<%= @user.id %>'>
            <%= render "layouts/follow", user: @user %>
          </div>
        </div>
      </div>
    </div>

    <div class="card-body">
      <div class="row no-gutters border-bottom">
        <div class="col-3 pb-2" data-toggle="modal" data-target="#profile-image-modal">
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.png", class:"rounded-circle"; %>
        </div>
        <div class="modal fade" id="profile-image-modal" tabindex="-1">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-body">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= attachment_image_tag @user, :profile_image, fallback: "no_image.png", class:"rounded-circle img-fluid"; %>
          　   </div>
            </div>
          </div>
        </div>
        <div class="col-3 small text-center"><a href="#index" class="deco-none">投稿</br><%= @user.contents.count %></a></div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followings_path(@user), class: "deco-none" do %>
              フォロー</br><div id="following-count_<%= @user.id %>"><%= @user.followings.count %></div>
            <% end %>
          </div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followers_path(@user), class: "deco-none" do %>
              フォロワー</br><div id="follower-count_<%= @user.id %>"><%= @user.followers.count %></div>
            <% end %>
          </div>
      </div>
        <div class="row pt-2">

          <div class="col-4 pr-0">
            <p><%= @user.user_name %>
            <% if @user == current_user %>
              <%= link_to terms_path do %>
                <br><span class="text-black-50 small"><i class="far fa-list-alt"></i></span>
              <% end %>
            <% end %>
            </p>
          </div>

          <div class="col-6 pl-2 pr-0">
            <p class="text-black-50 small"><%= @user.created_at.to_s(:datetime_jp) %>から</br>
            PAKUPAKUを利用しています
            </p>
          </div>

          <div class="col-2 pr-2 pl-0" id="room-icon_<%= @user.id %>">
            <%= render "layouts/room", {user: @user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry} %>
          </div>

      </div>
      <div class="row">
        <div class="col-12">
          <%= @user.introduction %>
        </div>
      </div>
    </div>
  </div>
  <%= render "layouts/user_nav" %>
  <div id="index"><%= render "layouts/contents_index", contents: @contents %></div>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @contents %>
  </div>
  <%= render "layouts/footer" %>
</div>

<script>
  $(function(){
  $('a[href^="#"]').click(function(){
    let speed = 400;
    let href= $(this).attr("href");
    let target = $(href == "#" || href == "" ? 'html' : href);
    let position = target.offset().top;
    $("html, body").animate({scrollTop:position}, speed, "swing");
    return false;
  });
});
</script>

app/views/users/show_favorite.html.erb
<%= render "layouts/user_share" %>

app/views/users/show_like.html.erb
<%= render "layouts/user_share" %>

app/views/users/user_favorites.html.erb
<%= render "layouts/user_share" %>

app/views/users/user_followers.html.erb
<%= render "layouts/user_follow_index" %>

app/views/users/user_followings.html.erb
<%= render "layouts/user_follow_index" %>

app/views/users/user_likes.html.erb
<%= render "layouts/user_share" %>