config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get      'users/terms'          => 'users#terms',         as: 'terms'
  get      '/contents/index_age0' => 'contents#index_age0', as: 'contents_age0'
  get      '/contents/index_age1' => 'contents#index_age1', as: 'contents_age1'
  get      '/contents/index_age2' => 'contents#index_age2', as: 'contents_age2'
  get      '/contents/index_age3' => 'contents#index_age3', as: 'contents_age3'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    confirmations:      'users/confirmations'
                                    }
  resources :contents,   only:[:new, :create, :index, :show, :update, :destroy] do
    resource :likes,     only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
    resource :comments,  only:[:create]
    delete '/comments/:id' => 'comments#destroy', as: 'destroy_comments'
    collection do
      get 'search'
    end
  end
  resources :users,      only:[:index, :show, :update, :destroy] do
    get 'user_likes'      => 'users#user_likes'
    get 'user_favorites'  => 'users#user_favorites'
    get 'user_followings' => 'users#user_followings'
    get 'user_followers'  => 'users#user_followers'
    collection do
      get 'search'
    end
  end
  resources :relationships, only:[:create, :destroy]
  resources :messages,      only:[:create]
  resources :rooms,         only:[:create,:show]
  resources :notifications, only:[:index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_comment.html.erb
<%= form_with model: comment, url: {controller: 'comments', action: 'create', content_id: content.id }, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="row">
    <div class="col-9">
      <%= f.text_field :comment, placeholder: "コメントを入力", class: "form-control" %>
    </div>
      <%= f.hidden_field :content_id, :value => content.id %>
    <div class="col-2 pl-0">
      <%= f.submit "送信", class: "btn btn-outline-secondary mr-2" %>
    </div>
  </div>
<% end %>

app/views/layouts/_content_edit.html.erb
<div class="modal fade" id="content-edit-modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= form_with model:@content, local:true do |f| %>
        
          <div class="form-group row mt-5">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :画像 %></label>
            <div class="col-md-6">
              <%= f.attachment_field :content_images_images, multiple: true %>
            </div>
          </div>
      
          <div class="form-group row mt-3">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :キャプション %></label>
            <div class="col-md-6">
              <%= f.text_area :body, class: "form-control" %>
            </div>
          </div>
      
          <div class="form-group row">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :お子様の年齢 %></label>
            <div class="col-md-6 pt-2">
              <%= f.select :target_age, ['0歳', '1歳', '2歳', '3歳', '4歳以上'], { include_blank: '選択してください'}, {class: 'form-control'} %>
              <small class="form-text">※ 投稿の対象としたいお子様のご年齢を選択してください</small>
            </div>
          </div>
          
          <div class="row">
            <div class="col-6 offset-1 text-left">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            <div class="col-4">
              <%= f.submit "変更", class: "btn btn-info mb-4" %>
            </div>
          </div>
          
        <% end %>
  　   </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <div class="fade show alert alert-warning d-flex">
          <li><%= message %></li>
          <button class="close ml-auto" data-dismiss="alert"> &times; </button>
        </div>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_favorite.html.erb
<% if content.favorited_by?(current_user) %>
    <%= link_to content_favorites_path(content), method: :delete, remote: true, class: "deco-none" do %>
      <h5 class="favorited fas fa-star mr-1 pb-2"></h5><%= content.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to content_favorites_path(content), method: :post, remote: true, class: "deco-none" do %>
      <h5 class="far fa-star mr-1 pb-2"></h5><%= content.favorites.count %>
    <% end %>
<% end %>

app/views/layouts/_follow.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote: true, data: {"turbolinks" => false}) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit '解除', class: 'btn btn-outline-secondary btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build, remote: true, data: {"turbolinks" => false}) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー', class: 'btn btn-outline-info btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="card fixed-bottom">
  <div class="card-body col-lg-6 offset-lg-3 mx-auto px-0">
    <div class="row text-center">
      
      <div class="col-2 offset-1">
        <% if current_page?(new_content_path) %>
          <h3 class="fas fa-pencil-alt selected-icon"></h3>
        <% else %>
          <%= link_to new_content_path, class: "deco-none-footer" do %>
            <h3 class="fas fa-pencil-alt" data-toggle="tooltip" title="新規投稿" data-placement="bottom"></h3>
          <% end %>
        <% end %>
      </div>
      
      <div class="col-2">
        <% if current_page?(user_path(current_user)) %>
          <h3 id="scroll" class="fas fa-home selected-icon" ></h3>
        <% else %>
          <%= link_to user_path(current_user), class: "deco-none-footer" do %>
            <h3 class="fas fa-home" data-toggle="tooltip" title="マイページ" data-placement="bottom"></h3>
          <% end %>
        <% end %>
      </div>
      
      <div class="col-2">
        <% if current_page?(users_path) %>
          <h3 id="scroll" class="fas fa-users selected-icon" ></h3>
        <% else %>
          <%= link_to users_path, class: "deco-none-footer" do %>
            <h3 class="fas fa-users" data-toggle="tooltip" title="ユーザー一覧" data-placement="bottom"></h3>
          <% end %>
        <% end %>
      </div>
      
      <div class="col-2">
        <% if current_page?(contents_path) %>
          <h3 id="scroll" class="fas fa-utensil-spoon selected-icon"></h3>
        <% else %>
          <%= link_to contents_path, class: "deco-none-footer" do %>
            <h3 class="fas fa-utensil-spoon" data-toggle="tooltip" title="投稿一覧" data-placement="bottom"></h3>
          <% end %>
        <% end %>
      </div>
      
      <% if current_page?(notifications_path) %>
        <div class="col-2">
          <h3 class="fas fa-bell selected-icon"></h3>
        </div>
      <% else %>
        <div class="col-2">
          <%= link_to notifications_path, class: "deco-none-footer" do %>
            <% if unchecked_notifications.any? %>
              <h3 class="fas fa-bell fa-stack-2x" data-toggle="tooltip" title="通知" data-placement="bottom"></h3>
              <i class="fas fa-circle n-circle fa-stack-1x"></i>
            <% else %>
              <h3 class="fas fa-bell" data-toggle="tooltip" title="通知" data-placement="bottom"></h3>
            <% end %>
          <% end %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

<script>
  $('[data-toggle="tooltip"]').tooltip();
</script>

app/views/layouts/_index_age.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <%= render "layouts/nav" %>
  <%= render "layouts/contents_index", contents: @contents %>
  <div class="col-lg-6 offset-lg-3 mx-auto mt-4">
    <%= paginate @contents %>
  </div>
  <%= render "layouts/footer" %>
</div>

app/views/layouts/_like.html.erb
<% if content.liked_by?(current_user) %>
    <%= link_to content_likes_path(content), method: :delete, remote: true, class: "deco-none" do %>
      <h5 class="liked fas fa-heart mr-1 pb-2"></h5><%= content.likes.count %>
    <% end %>
  <% else %>
    <%= link_to content_likes_path(content), method: :post, remote: true, class: "deco-none" do %>
      <h5 class="far fa-heart mr-1 pb-2"></h5><%= content.likes.count %>
    <% end %>
<% end %>

app/views/layouts/_notifications.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="border-bottom">
  <div class="form-inline mt-4">
    <div class="col-3">
      <%= link_to user_path(visitor) do %>
        <%= attachment_image_tag visitor, :profile_image, :fill, 30, 30, fallback: "no_image.png", class:"rounded-circle"; %>
      <% end %>
    </div>
    <div class="col-9 font-weight-bold">
      <%= visitor.user_name %>
      さんが
      <% case notification.action %>
        <% when 'follow' then %>
          あなたをフォローしました
        <% when 'like' then %>
          <%= link_to 'あなたの投稿', notification.content, style: "font-weight: bold;", class: "deco-none" %>
          にいいねしました
        <% when 'favorite' then %>
          <%= link_to 'あなたの投稿', notification.content, style: "font-weight: bold;", class: "deco-none" %>
          にお気に入りしました
        <% when 'comment' then %>
          <% if notification.content.user_id == visited.id %>
            <%= link_to "あなたの投稿", notification.content, style: "font-weight: bold;", class: "deco-none" %>
            にコメントしました
        <% end %>
        <% when 'message' then %>
          メッセージを送信しました
      <% end %>
      <div class="small text-muted text-right pl-3">
        <% case notification.action %>
          <% when 'like' then %>
            <i class="liked fas fa-heart mr-2 pb-2"></i>
          <% when 'favorite' then %>
            <i class="favorited fas fa-star mr-2 pb-2"></i>
        <% end %>
        <%= time_ago_in_words(notification.created_at).upcase %>前
      </div>
    </div>
  </div>
</div>

app/views/layouts/_room.html.erb
<% unless user.id == current_user.id %>
  <% if (current_user.following?(user)) && (user.following?(current_user)) %>
    <% if isRoom == true %>
      <a href="/rooms/<%= roomId %>" class="deco-none"><h5 class="far fa-envelope pt-2 ml-2"></h5></a>
    <% else %>
      <%= form_for room do |f| %>
        <%= fields_for entry do |e| %>
          <%= e.hidden_field :user_id, value: user.id %>
        <% end %>
        <%= button_tag :type => "submit", :class =>"btn btn-default" do %>
          <h5 class="far fa-envelope"></h5>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<!--<#% unless @user.id == current_user.id %>-->
<!--  <#% if (current_user.following?(@user)) && (@user.following?(current_user)) %>-->
<!--    <#% if @isRoom == true %>-->
<!--      <a href="/rooms/<%#= @roomId %>" class="deco-none"><h5 class="far fa-envelope pt-2"></h5></a>-->
<!--    <#% else %>-->
<!--      <#%= form_for @room do |f| %>-->
<!--        <#%= fields_for @entry do |e| %>-->
<!--          <#%= e.hidden_field :user_id, value: @user.id %>-->
<!--        <%# end %>-->
<!--        <%#= button_tag :type => "submit", :class =>"btn btn-default" do %>-->
<!--          <h5 class="far fa-envelope"></h5>-->
<!--        <%# end %>-->
<!--      <%# end %>-->
<!--    <%# end %>-->
<!--  <%# end %>-->
<!--<%# end %>-->

app/views/layouts/_user_edit.html.erb
<div class="modal fade" id="profile-edit-modal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-body text-center">
        <%= form_with model:@user, local:true do |f| %>

          <div class="form-group row mt-5">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :ユーザー名 %></label>
            <div class="col-md-6">
              <%= f.text_field :user_name, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :性別 %></label>
            <div class="col-md-6 pt-2">
              <div class="form-check form-check-inline mr-4">
                <%= f.radio_button :sex, :"男性" %>
                <label class="form-check-label">男性</label>
              </div>
              <div class="form-check form-check-inline mr-4">
                <%= f.radio_button :sex, :"女性" %>
                <label class="form-check-label">女性</label>
              </div>
              <div class="form-check form-check-inline mr-4">
                <%= f.radio_button :sex, :"どちらでもない" %>
                <label class="form-check-label">どちらでもない</label>
              </div>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :生年月日 %></label>
            <div class="col-md-6 pt-2">
              <%= f.date_select :birthday, use_month_numbers: true, start_year: 1950, end_year: (Time.now.year - 15), default: Date.new(1989, 1, 1) %>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :プロフィール画像 %></label>
            <div class="col-md-6">
              <div class="user_edit_image_btn">
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", id: "file" %>
              </div>
              <div id="user_img_field" onClick="$('#file').click()" >
                <p>画像選択</p>
              </div>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :自己紹介 %></label>
            <div class="col-md-6">
              <%= f.text_area :introduction, class: "form-control" %>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :お子様の性別 %></label>
            <div class="col-md-6 pt-2">
              <div class="form-check form-check-inline mr-4">
                <%= f.radio_button :child_gender, :"男の子" %>
                <label class="form-check-label">男の子</label>
              </div>
              <div class="form-check form-check-inline mr-4">
                <%= f.radio_button :child_gender, :"女の子" %>
                <label class="form-check-label">女の子</label>
              </div>
            </div>
          </div>

          <div class="form-group row pt-4">
            <label class="col-md-4 col-form-label text-md-right"><%= f.label :お子様の年齢 %></label>
            <div class="col-md-6 pt-2">
              <%= f.select :child_age, ['0歳', '1歳', '2歳', '3歳', '4歳以上'], { include_blank: '選択してください'}, {class: 'form-control'} %>
            </div>
          </div>

          <div class="row">
            <div class="col-5 offset-1 text-left">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            <div class="col-5">
              <%= f.submit "変更", class: "btn btn-info mb-4" %>
            </div>
          </div>

        <% end %>
  　   </div>
    </div>
  </div>
</div>

app/views/layouts/_user_follow_index.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <% @users.each do |user| %>
    <div class="card col-lg-6 offset-lg-3 mx-auto mt-4 px-0">
      <div class="card-header bg-white">
        <div class="row">
          <div class="col-7">
            <%= link_to user_path(user), class: "deco-none" do %>
              <h6 class="text-left font-weight-bold"><%= user.user_name %></h6>
            <% end %>
          </div>
          <div class="col-5" id='follow-button_<%= user.id %>'>
            <%= render "layouts/follow", user: user %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row no-gutters border-bottom">
          <div class="col-3 pb-3">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.png", class:"rounded-circle"; %>
            <% end %>
          </div>
          <div class="col-3 small text-center">投稿数</br><%= user.contents.count %></div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followings_path(user), class: "deco-none" do %>
              フォロー</br><div id="following-count_<%= user.id %>"><%= user.followings.count %></div>
            <% end %>
          </div>
          <div class="col-3 small text-center">
            <%= link_to user_user_followers_path(user), class: "deco-none" do %>
              フォロワー</br><div id="follower-count_<%= user.id %>"><%= user.followers.count %></div>
            <% end %>
          </div>
        </div>
        <div class="row p-2">
          <div class="col-4">
            <%= user.user_name %>
          </div>
          <div class="col-8">
            <p class="text-black-50 small"><%= user.created_at.to_s(:datetime_jp) %>から</br>
            PAKUPAKUを利用しています
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <%= user.introduction %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= render "layouts/footer" %>
</div>

app/views/layouts/_user_nav.html.erb
<div class="col-lg-6 offset-lg-3 mx-auto mt-2 px-0">
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item small"><%= link_to "投稿",       user_path(@user.id),               class: "nav-link active deco-none" %></li>
    <li class="nav-item small"><%= link_to "いいね",     user_user_likes_path(@user.id),     class: "nav-link deco-none" %></li>
    <li class="nav-item small"><%= link_to "お気に入り", user_user_favorites_path(@user.id), class: "nav-link deco-none" %></li>
  </ul>
</div>

app/views/layouts/_user_share.html.erb
<div class="container" style="padding-bottom: 5rem;">
  <%= render "layouts/user_nav" %>
  <% @contents.each do |content| %>
    <div class="card col-lg-6 offset-lg-3 mx-auto px-0 mt-3">
      <div class="card-header">
        <div class="row">
          <%= link_to user_path(content.content.user), class: "deco-none" do %>
            <%= attachment_image_tag content.content.user, :profile_image, :fill, 40, 40, fallback: "no_image.png", class:"rounded-circle"; %>
          <% end %>
          <div class="col-5 text-left font-weight-bold">
            <%= link_to user_path(content.content.user), class: "deco-none" do %>
              <%= content.content.user.user_name %>
            <% end %>
          </div>
          <div class="col-5 text-right">
            <div class ="text-black-50"><%= content.content.target_age %>向けの投稿</div>
          </div>
        </div>
      </div>
      <% if content.content.content_images.present? %>
        <div class="slider">
          <% content.content.content_images.each do |image| %>
            <%= link_to content_path(content.content.id) do %>
              <%= attachment_image_tag image, :image, class:"card-img-top"; %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <div class="card-body pt-4">
        <%= link_to content_path(content.content.id), class: "deco-none" do %>
          <div class="card-text border-bottom pt-3"><%= raw Rinku.auto_link(simple_format(content.content.body)) %></div>
        <% end %>
        <div class="row pt-4">
          <div class="col-4">
            <div class="text-black-50 small"><%= date_format(content.created_at) %></div>
          </div>
          <div class="col-8">
          <div class="row">
            <div id='like-button_<%= content.id %>' class="col-6 text-right">
            <%= render "layouts/like", content: content.content %>
            </div>
            <div id='favorite-button_<%= content.id %>' class="col-6">
              <%= render "layouts/favorite", content: content.content %>
            </div>
          </div>
        </div>
        </div>
        <%= render "layouts/comment", comment: @comment, content: content.content %>
      </div>
    </div>
  <% end %>
  <%= render "layouts/footer" %>
</div>